[package]
name = "bidiff"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
oipss = { path = "../oipss" }
async-std = "0.99.12"
log = "0.4.8"
suffix_array = "0.4.0"
