[package]
name = "bipatch"
version = "0.1.0"
description = "A bsdiff-derived binary patching tool - patch library"
license = "Apache-2.0 OR MIT"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = { version = "1.3.2" }
integer-encoding = { version = "1.0.7" }
