[package]
name = "bipatch"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = { version = "1.3.2" }
integer-encoding = { version = "1.0.7" }
brotli = { version = "3.3.0" }
thiserror = "1.0.5"
failure = "0.1.6"
