[package]
name = "bic"
version = "0.1.0"
description = "A bsdiff-derived binary patching tool - example CLI tool"
license = "Apache-2.0 OR MIT"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
bidiff = { path = "../bidiff", features = ["enc"] }
bipatch = { path = "../bipatch" }

log = "0.4.8"
env_logger = "0.7.1"
byteorder = "1.3.2"
integer-encoding = "1.0.7"
hmac-sha256 = "0.1.2"
size = "0.1.2"
pipe = "0.2.0"
crossbeam-utils = "0.7.0"
argh = "0.1.3"
anyhow = "1.0.26"

[dependencies.comde]
version = "0.1.0"
default-features = false
features = ["snappy", "deflate", "zstandard", "brotli"]
