[package]
name = "bidiff"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[features]
default = ["enc"]
enc = ["byteorder", "integer-encoding"]

[dependencies]
# for enc
byteorder = { version = "1.3.2", optional = true }
integer-encoding = { version = "1.0.7", optional = true }

# other deps
log = "0.4.8"
sacabase = "2.0.0"
sacapart = "2.0.0"
divsufsort = "2.0.0"
rayon = "1.2.1"

[dev-dependencies]
proptest = "0.9.4"

