[package]
name = "bidiff"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[features]
default = ["enc"]
enc = ["byteorder", "integer-encoding", "brotli"]

[dependencies]
log = "0.4.8"
divsufsort = "1.0.2"

# for enc
byteorder = { version = "1.3.2", optional = true }
integer-encoding = { version = "1.0.7", optional = true }
brotli = { version = "3.3.0", optional = true }

